// Auto-generated food data for Food Guessing Game
// Generated by CSV Import Database Manager

export interface Food {
  name: string;
  imageUrls: string[];
  originCity: string;
  originCityLat: number;
  originCityLng: number;
  description: string;
}

export interface Country {
  name: string;
  foods: Food[];
}

export const countries: Country[] = [
  {
    name: "Lebanon",
    foods: [
      {
        name: "Kibbeh",
        imageUrls: [],
        originCity: "Beirut",
        originCityLat: 33.8938,
        originCityLng: 35.5018,
        description: "A traditional Lebanese dish made with bulgur, meat, and spices. This versatile dish represents the country's mastery of grain preparation and its love for bold, complex flavors."
      },
      {
        name: "Fattoush",
        imageUrls: [],
        originCity: "Beirut",
        originCityLat: 33.8938,
        originCityLng: 35.5018,
        description: "A Lebanese salad made with mixed vegetables and pita bread. This refreshing salad represents the country's love for fresh ingredients and its mastery of simple yet flavorful combinations."
      },
      {
        name: "Hummus",
        imageUrls: [],
        originCity: "Beirut",
        originCityLat: 33.8938,
        originCityLng: 35.5018,
        description: "A dip made from chickpeas, tahini, and lemon juice. This popular dish represents the country's mastery of simple preparations and its influence on global cuisine."
      }
    ]
  },
  {
    name: "Indonesia",
    foods: [
      {
        name: "Gado-gado",
        imageUrls: ["https://drive.google.com/file/d/1hLma0OrTReFMLXV7ym5xQr4qee8f2CoV/view?usp=drivesdk"],
        originCity: "Jakarta",
        originCityLat: -6.2088,
        originCityLng: 106.8456,
        description: "A vegetable salad with peanut sauce that's a popular Indonesian dish. This refreshing salad represents the country's love for fresh vegetables and its mastery of complex, flavorful sauces."
      },
      {
        name: "Rendang",
        imageUrls: [],
        originCity: "Jakarta",
        originCityLat: -6.2088,
        originCityLng: 106.8456,
        description: "A slow-cooked beef curry that's considered Indonesia's national dish. This complex dish represents the country's mastery of spice blends and its love for bold, aromatic flavors."
      },
      {
        name: "Nasi Goreng",
        imageUrls: [],
        originCity: "Jakarta",
        originCityLat: -6.2088,
        originCityLng: 106.8456,
        description: "Indonesian fried rice that's a staple of the country's cuisine. This versatile dish represents the country's mastery of rice cooking and its love for bold, flavorful combinations."
      }
    ]
  },
  {
    name: "Poland",
    foods: [
      {
        name: "Żurek",
        imageUrls: [],
        originCity: "Warsaw",
        originCityLat: 52.2297,
        originCityLng: 21.0122,
        description: "A sour rye soup that's a traditional Polish dish. This hearty soup represents the country's mastery of fermentation and its love for bold, tangy flavors."
      },
      {
        name: "Bigos",
        imageUrls: [],
        originCity: "Warsaw",
        originCityLat: 52.2297,
        originCityLng: 21.0122,
        description: "A hunter's stew made with various meats and sauerkraut. This complex dish represents the country's love for hearty meals and its mastery of slow-cooking techniques."
      },
      {
        name: "Pierogi",
        imageUrls: [],
        originCity: "Warsaw",
        originCityLat: 52.2297,
        originCityLng: 21.0122,
        description: "Dumplings filled with various ingredients that are a staple of Polish cuisine. This versatile dish represents the country's mastery of dough-making and its love for comforting, satisfying foods."
      }
    ]
  },
  {
    name: "Norway",
    foods: [
      {
        name: "Smalahove",
        imageUrls: [],
        originCity: "Oslo",
        originCityLat: 59.9139,
        originCityLng: 10.7522,
        description: "A traditional Norwegian dish made with sheep's head. This hearty dish represents the country's resourceful use of all parts of the animal and its mastery of traditional cooking techniques."
      },
      {
        name: "Rakfisk",
        imageUrls: [],
        originCity: "Oslo",
        originCityLat: 59.9139,
        originCityLng: 10.7522,
        description: "Fermented trout that's a traditional Norwegian delicacy. This acquired taste represents the country's mastery of fermentation techniques and its love for bold, traditional flavors."
      },
      {
        name: "Lutefisk",
        imageUrls: [],
        originCity: "Oslo",
        originCityLat: 59.9139,
        originCityLng: 10.7522,
        description: "Dried fish that's been treated with lye and then cooked. This traditional dish represents the country's mastery of preservation techniques and its love for unique textures."
      }
    ]
  },
  {
    name: "Portugal",
    foods: [
      {
        name: "Francesinha",
        imageUrls: [],
        originCity: "Lisbon",
        originCityLat: 38.7223,
        originCityLng: -9.1393,
        description: "A sandwich with multiple types of meat and cheese, covered in a beer-based sauce. This hearty dish represents the country's love for bold flavors and its mastery of combining different ingredients."
      },
      {
        name: "Bacalhau à Brás",
        imageUrls: [],
        originCity: "Lisbon",
        originCityLat: 38.7223,
        originCityLng: -9.1393,
        description: "A traditional Portuguese dish made with salted cod and potatoes. This classic dish represents the country's maritime heritage and its mastery of preserving techniques."
      },
      {
        name: "Pastel de Nata",
        imageUrls: [],
        originCity: "Lisbon",
        originCityLat: 38.7223,
        originCityLng: -9.1393,
        description: "A custard tart that's a beloved Portuguese dessert. This elegant pastry represents the country's mastery of baking techniques and its love for simple yet sophisticated sweets."
      }
    ]
  },
  {
    name: "Turkey",
    foods: [
      {
        name: "Kuzu Kelle",
        imageUrls: [],
        originCity: "Istanbul",
        originCityLat: 41.0082,
        originCityLng: 28.9784,
        description: "A traditional Turkish dish made with lamb head. This hearty dish represents the country's resourceful use of all parts of the animal and its mastery of bold, complex flavors."
      },
      {
        name: "Baklava",
        imageUrls: [],
        originCity: "Istanbul",
        originCityLat: 41.0082,
        originCityLng: 28.9784,
        description: "A sweet pastry made with layers of phyllo dough and nuts. This elegant dessert represents the country's mastery of pastry-making and its love for rich, sweet flavors."
      },
      {
        name: "Doner Kebab",
        imageUrls: [],
        originCity: "Istanbul",
        originCityLat: 41.0082,
        originCityLng: 28.9784,
        description: "Meat cooked on a vertical rotisserie and served in bread. This popular dish represents the country's mastery of grilling techniques and its influence on global cuisine."
      }
    ]
  },
  {
    name: "Egypt",
    foods: [
      {
        name: "Feseekh",
        imageUrls: [],
        originCity: "Cairo",
        originCityLat: 30.0444,
        originCityLng: 31.2357,
        description: "Fermented fish that's a traditional Egyptian delicacy. This acquired taste represents the country's mastery of fermentation techniques and its love for bold, traditional flavors."
      },
      {
        name: "Ful Medames",
        imageUrls: [],
        originCity: "Cairo",
        originCityLat: 30.0444,
        originCityLng: 31.2357,
        description: "A stew of fava beans that's considered Egypt's national dish. This hearty dish represents the country's love for simple, nourishing meals and its mastery of legume preparation."
      },
      {
        name: "Koshary",
        imageUrls: [],
        originCity: "Cairo",
        originCityLat: 30.0444,
        originCityLng: 31.2357,
        description: "A street food dish made with rice, lentils, and pasta. This filling dish represents the country's love for hearty meals and its mastery of combining different grains and legumes."
      }
    ]
  },
  {
    name: "UK",
    foods: [
      {
        name: "Stargazy Pie",
        imageUrls: [],
        originCity: "London",
        originCityLat: 51.5074,
        originCityLng: -0.1278,
        description: "A Cornish pie with fish heads protruding through the crust, looking at the stars. This unusual dish represents the maritime heritage of Cornwall and the country's unique regional specialties."
      },
      {
        name: "Haggis",
        imageUrls: [],
        originCity: "London",
        originCityLat: 51.5074,
        originCityLng: -0.1278,
        description: "A traditional Scottish dish made with sheep's heart, liver, and lungs, mixed with oats and spices. This hearty dish represents the resourcefulness of Scottish cuisine and the country's mastery of using every part of the animal."
      },
      {
        name: "Fish and Chips",
        imageUrls: [],
        originCity: "London",
        originCityLat: 51.5074,
        originCityLng: -0.1278,
        description: "A British dish of battered fish and deep-fried potatoes. This iconic meal represents the heartiness of British cuisine and the country's love for simple, satisfying comfort foods."
      }
    ]
  },
  {
    name: "New Zealand",
    foods: [
      {
        name: "Kina",
        imageUrls: [],
        originCity: "Auckland",
        originCityLat: -36.8485,
        originCityLng: 174.7633,
        description: "Sea urchin that's a traditional Maori delicacy. This unique seafood represents the country's connection to the ocean and its mastery of using local ingredients."
      },
      {
        name: "Pavlova",
        imageUrls: [],
        originCity: "Auckland",
        originCityLat: -36.8485,
        originCityLng: 174.7633,
        description: "A meringue-based dessert that's a source of national pride. This elegant dessert represents the country's love for simple yet sophisticated sweets and its mastery of baking techniques."
      },
      {
        name: "Hāngi",
        imageUrls: [],
        originCity: "Auckland",
        originCityLat: -36.8485,
        originCityLng: 174.7633,
        description: "A traditional Maori method of cooking food in an earth oven. This ancient technique represents the country's indigenous culinary traditions and its mastery of slow-cooking methods."
      }
    ]
  },
  {
    name: "Nigeria",
    foods: [
      {
        name: "Isi Ewu",
        imageUrls: [],
        originCity: "Lagos",
        originCityLat: 6.5244,
        originCityLng: 3.3792,
        description: "A spicy goat head stew that's a traditional Nigerian delicacy. This hearty dish represents the country's resourceful use of all parts of the animal and its mastery of bold, complex flavors."
      },
      {
        name: "Suya",
        imageUrls: [],
        originCity: "Lagos",
        originCityLat: 6.5244,
        originCityLng: 3.3792,
        description: "Spiced meat skewers that are a popular Nigerian street food. This flavorful dish represents the country's mastery of grilling techniques and its love for bold, aromatic spices."
      },
      {
        name: "Jollof Rice",
        imageUrls: [],
        originCity: "Lagos",
        originCityLat: 6.5244,
        originCityLng: 3.3792,
        description: "A one-pot rice dish that's a staple of West African cuisine. This versatile dish represents the country's mastery of rice cooking and its love for bold, flavorful combinations."
      }
    ]
  },
  {
    name: "Colombia",
    foods: [
      {
        name: "Hormigas Culonas",
        imageUrls: ["https://drive.google.com/file/d/1jx4GJHAL3KCBB_qCheFPhOPowd6YduFa/view?usp=drivesdk", "https://drive.google.com/file/d/1QpteXgoFdKbarAz5eNchQFJXQ9VSPB2A/view?usp=drivesdk", "https://drive.google.com/file/d/1LQCaOkcQB028ccorx6j5x-3TZM0POmh9/view?usp=drivesdk"],
        originCity: "Bogotá",
        originCityLat: 4.711,
        originCityLng: -74.0721,
        description: "Large ants that are roasted and eaten as a snack. This unique delicacy represents the country's adventurous palate and its mastery of using local ingredients."
      },
      {
        name: "Ajiaco",
        imageUrls: ["https://drive.google.com/file/d/1sJoE0FR06ESz_JK_mfLCZV51_l68FbAh/view?usp=drivesdk", "https://drive.google.com/file/d/1EkK-YpakgudlGnQM4bC5WFndjzD61Eg8/view?usp=drivesdk"],
        originCity: "Bogotá",
        originCityLat: 4.711,
        originCityLng: -74.0721,
        description: "A chicken and potato soup that's considered Colombia's national dish. This hearty soup represents the country's love for comforting meals and its mastery of complex, layered flavors."
      },
      {
        name: "Bandeja Paisa",
        imageUrls: [],
        originCity: "Bogotá",
        originCityLat: 4.711,
        originCityLng: -74.0721,
        description: "A hearty platter with beans, rice, meat, and plantains. This filling dish represents the country's love for substantial meals and its mastery of combining different flavors and textures."
      }
    ]
  },
  {
    name: "Sweden",
    foods: [
      {
        name: "Surströmming",
        imageUrls: [],
        originCity: "Stockholm",
        originCityLat: 59.3293,
        originCityLng: 18.0686,
        description: "Fermented herring that's known for its strong smell. This acquired taste represents the country's mastery of fermentation techniques and its love for bold, traditional flavors."
      },
      {
        name: "Gravlax",
        imageUrls: [],
        originCity: "Stockholm",
        originCityLat: 59.3293,
        originCityLng: 18.0686,
        description: "Cured salmon that's a traditional Swedish delicacy. This elegant dish represents the country's mastery of curing techniques and its love for fresh, simple preparations."
      },
      {
        name: "Köttbullar",
        imageUrls: [],
        originCity: "Stockholm",
        originCityLat: 59.3293,
        originCityLng: 18.0686,
        description: "Swedish meatballs that are a beloved comfort food. This iconic dish represents the country's love for hearty, satisfying meals and its mastery of simple yet flavorful techniques."
      }
    ]
  },
  {
    name: "Argentina",
    foods: [
      {
        name: "Morcilla Blood Sausage",
        imageUrls: ["https://drive.google.com/file/d/13IaOVQgWL__tHJsuJAnzif86l1FfbiuI/view?usp=drivesdk", "https://drive.google.com/file/d/1V_nyTO02vNZxBXNUe4bIK8YP13CcGAUo/view?usp=drivesdk", "https://drive.google.com/file/d/19y1Q_dodg9Oz1R5aEH9WRJgSjAKaQbk4/view?usp=drivesdk"],
        originCity: "Buenos Aires",
        originCityLat: -34.6118,
        originCityLng: -58.396,
        description: "A blood sausage that's a staple of Argentine cuisine. This hearty dish represents the country's love for bold flavors and its mastery of sausage-making techniques."
      },
      {
        name: "Empanadas",
        imageUrls: ["https://drive.google.com/file/d/1uQg07F5gXH5EVBOu6sgVTvLxOAcUQZv6/view?usp=drivesdk"],
        originCity: "Buenos Aires",
        originCityLat: -34.6118,
        originCityLng: -58.396,
        description: "Stuffed pastries that are a popular snack throughout Latin America. This versatile dish represents the country's mastery of pastry-making and its love for portable, satisfying foods."
      },
      {
        name: "Asado",
        imageUrls: ["https://drive.google.com/file/d/10u-HIMU-VIC5RyArxcAk7Iwe4WGusVbD/view?usp=drivesdk", "https://drive.google.com/file/d/1Xs--XzRUlHpoQ0z8F8vbm8RF6wbn4VRT/view?usp=drivesdk"],
        originCity: "Buenos Aires",
        originCityLat: -34.6118,
        originCityLng: -58.396,
        description: "A traditional Argentine barbecue that's a social event. This iconic dish represents the country's mastery of grilling techniques and its love for communal dining."
      }
    ]
  },
  {
    name: "Morocco",
    foods: [
      {
        name: "Khlii",
        imageUrls: [],
        originCity: "Casablanca",
        originCityLat: 33.5731,
        originCityLng: -7.5898,
        description: "Preserved meat that's dried and stored in fat. This traditional food represents the country's mastery of preservation techniques and its resourceful use of meat."
      },
      {
        name: "Couscous",
        imageUrls: [],
        originCity: "Casablanca",
        originCityLat: 33.5731,
        originCityLng: -7.5898,
        description: "Steamed semolina grains that are a staple of North African cuisine. This versatile dish represents the country's mastery of grain preparation and its importance in Moroccan dining culture."
      },
      {
        name: "Tagine",
        imageUrls: [],
        originCity: "Casablanca",
        originCityLat: 33.5731,
        originCityLng: -7.5898,
        description: "A slow-cooked stew named after the earthenware pot it's cooked in. This traditional dish represents the country's mastery of slow-cooking techniques and its love for complex, aromatic flavors."
      }
    ]
  },
  {
    name: "South Africa",
    foods: [
      {
        name: "Mopane Worms",
        imageUrls: [],
        originCity: "Cape Town",
        originCityLat: -33.9249,
        originCityLng: 18.4241,
        description: "Large caterpillars that are dried and eaten as a snack. This traditional food represents the resourcefulness of South African cuisine and the country's mastery of using local ingredients."
      },
      {
        name: "Biltong",
        imageUrls: [],
        originCity: "Cape Town",
        originCityLat: -33.9249,
        originCityLng: 18.4241,
        description: "Dried, cured meat that's a popular South African snack. This traditional food represents the country's mastery of preservation techniques and its love for bold, salty flavors."
      },
      {
        name: "Bobotie",
        imageUrls: [],
        originCity: "Cape Town",
        originCityLat: -33.9249,
        originCityLng: 18.4241,
        description: "A spiced meat dish topped with an egg-based custard. This unique dish represents the fusion of Dutch and Malay influences in South African cuisine."
      }
    ]
  },
  {
    name: "Germany",
    foods: [
      {
        name: "Mett",
        imageUrls: [],
        originCity: "Berlin",
        originCityLat: 52.52,
        originCityLng: 13.405,
        description: "Raw minced pork seasoned with salt and pepper, often served on bread with onions. This traditional German dish represents the country's love for hearty, simple flavors and its mastery of meat preparation."
      },
      {
        name: "Sauerkraut",
        imageUrls: [],
        originCity: "Berlin",
        originCityLat: 52.52,
        originCityLng: 13.405,
        description: "Fermented cabbage that's a staple of German cuisine. This tangy side dish represents the importance of fermentation in German cooking and the country's mastery of preserving techniques."
      },
      {
        name: "Bratwurst",
        imageUrls: [],
        originCity: "Berlin",
        originCityLat: 52.52,
        originCityLng: 13.405,
        description: "German sausages made with pork, veal, or beef and various spices. This iconic dish represents the heart of German cuisine and the country's mastery of sausage-making techniques."
      }
    ]
  },
  {
    name: "Greece",
    foods: [
      {
        name: "Kokoretsi",
        imageUrls: [],
        originCity: "Athens",
        originCityLat: 37.9838,
        originCityLng: 23.7275,
        description: "A traditional Greek dish made with lamb or goat offal wrapped in intestines. This hearty dish represents the country's resourceful use of all parts of the animal and its mastery of bold flavors."
      },
      {
        name: "Souvlaki",
        imageUrls: [],
        originCity: "Athens",
        originCityLat: 37.9838,
        originCityLng: 23.7275,
        description: "Grilled meat skewers that are a staple of Greek cuisine. This simple dish represents the country's mastery of grilling techniques and its love for fresh, simple preparations."
      },
      {
        name: "Moussaka",
        imageUrls: [],
        originCity: "Athens",
        originCityLat: 37.9838,
        originCityLng: 23.7275,
        description: "A layered casserole made with eggplant, meat, and béchamel sauce. This iconic dish represents the sophistication of Greek cuisine and the country's mastery of complex layering techniques."
      }
    ]
  },
  {
    name: "Ethiopia",
    foods: [
      {
        name: "Kitfo",
        imageUrls: [],
        originCity: "Addis Ababa",
        originCityLat: 9.145,
        originCityLng: 38.7667,
        description: "Raw minced beef seasoned with spices and clarified butter. This traditional dish represents the bold flavors of Ethiopian cuisine and the country's mastery of spice combinations."
      },
      {
        name: "Injera",
        imageUrls: [],
        originCity: "Addis Ababa",
        originCityLat: 9.145,
        originCityLng: 38.7667,
        description: "A sourdough flatbread that's a staple of Ethiopian cuisine. This unique bread represents the country's mastery of fermentation and its importance in Ethiopian dining culture."
      },
      {
        name: "Doro Wat",
        imageUrls: [],
        originCity: "Addis Ababa",
        originCityLat: 9.145,
        originCityLng: 38.7667,
        description: "A spicy chicken stew that's considered Ethiopia's national dish. This complex dish represents the country's mastery of spice blends and its love for bold, aromatic flavors."
      }
    ]
  },
  {
    name: "Australia",
    foods: [
      {
        name: "Witchetty Grub",
        imageUrls: ["https://drive.google.com/file/d/1tXor411yJXOkHuIYXIByWHySKux1W_Dx/view?usp=drivesdk", "https://drive.google.com/file/d/1pTqjBa0gvXFK6Ntkxf-7llsxympeJjfZ/view?usp=drivesdk", "https://drive.google.com/file/d/1wJmLFR6Jgm5oAi2rVj8X_-4QolA5EGUf/view?usp=drivesdk"],
        originCity: "Sydney",
        originCityLat: -33.8688,
        originCityLng: 151.2093,
        description: "Large, white larvae that are eaten raw or cooked. This traditional Aboriginal food represents the ancient culinary traditions of Australia and the country's mastery of using local ingredients."
      },
      {
        name: "Lamington",
        imageUrls: ["https://drive.google.com/file/d/1IfirV8p-IHIIATrFE1ou5L2UZudjmcSH/view?usp=drivesdk", "https://drive.google.com/file/d/1dzdtF9Q11qoZkcGFpydTuk0ZNzNW83p6/view?usp=drivesdk"],
        originCity: "Sydney",
        originCityLat: -33.8688,
        originCityLng: 151.2093,
        description: "A sponge cake coated in chocolate and coconut. This beloved dessert represents the country's love for simple sweets and its mastery of traditional baking techniques."
      },
      {
        name: "Meat Pie",
        imageUrls: ["https://drive.google.com/file/d/1Lf9dZKT3rbmAp3-4Ba3fh5ZfJrKLCR3y/view?usp=drivesdk", "https://drive.google.com/file/d/10M533-ykQ8OxEk4W5XhoMf8E7skFo8iJ/view?usp=drivesdk", "https://drive.google.com/file/d/1FOiUglBBzsIwoJvkBT3fer9BcTWbyyAG/view?usp=drivesdk"],
        originCity: "Sydney",
        originCityLat: -33.8688,
        originCityLng: 151.2093,
        description: "A savory pie filled with minced meat and gravy. This iconic Australian dish represents the country's love for hearty comfort food and its mastery of pastry-making."
      }
    ]
  },
  {
    name: "Philippines",
    foods: [
      {
        name: "Balut",
        imageUrls: [],
        originCity: "Manila",
        originCityLat: 14.5995,
        originCityLng: 120.9842,
        description: "A fertilized duck egg that's boiled and eaten from the shell. This adventurous delicacy represents the bold flavors of Filipino cuisine and the country's mastery of unique textures."
      },
      {
        name: "Lechon",
        imageUrls: [],
        originCity: "Manila",
        originCityLat: 14.5995,
        originCityLng: 120.9842,
        description: "A whole roasted pig that's a centerpiece of Filipino celebrations. This festive dish represents the country's love for grand feasts and its mastery of roasting techniques."
      },
      {
        name: "Adobo",
        imageUrls: [],
        originCity: "Manila",
        originCityLat: 14.5995,
        originCityLng: 120.9842,
        description: "A Filipino dish of meat marinated in vinegar, soy sauce, and garlic. This national dish represents the heart of Filipino cuisine and the country's mastery of simple yet flavorful techniques."
      }
    ]
  },
  {
    name: "Brazil",
    foods: [
      {
        name: "Buchada de Bode",
        imageUrls: [],
        originCity: "São Paulo",
        originCityLat: -23.5505,
        originCityLng: -46.6333,
        description: "A traditional Brazilian dish made with goat stomach and intestines. This hearty dish represents the country's resourceful use of all parts of the animal and its mastery of bold, complex flavors."
      },
      {
        name: "Pão de Queijo",
        imageUrls: [],
        originCity: "São Paulo",
        originCityLat: -23.5505,
        originCityLng: -46.6333,
        description: "Cheese bread made with tapioca flour and cheese. This popular snack represents the fusion of indigenous and Portuguese influences in Brazilian cuisine."
      },
      {
        name: "Feijoada",
        imageUrls: [],
        originCity: "São Paulo",
        originCityLat: -23.5505,
        originCityLng: -46.6333,
        description: "A black bean stew with various cuts of pork. This national dish represents the heart of Brazilian cuisine and the country's mastery of slow-cooking techniques."
      }
    ]
  },
  {
    name: "Peru",
    foods: [
      {
        name: "Cuy",
        imageUrls: [],
        originCity: "Lima",
        originCityLat: -12.0464,
        originCityLng: -77.0428,
        description: "Roasted guinea pig that's a traditional Andean delicacy. This unique dish represents the ancient culinary traditions of Peru and the country's mastery of using local ingredients."
      },
      {
        name: "Lomo Saltado",
        imageUrls: [],
        originCity: "Lima",
        originCityLat: -12.0464,
        originCityLng: -77.0428,
        description: "A stir-fry dish that combines Chinese and Peruvian techniques. This fusion dish represents the multicultural nature of Peruvian cuisine and the country's ability to blend different culinary traditions."
      },
      {
        name: "Ceviche",
        imageUrls: [],
        originCity: "Lima",
        originCityLat: -12.0464,
        originCityLng: -77.0428,
        description: "Raw fish marinated in citrus juice and spices. This refreshing dish represents the coastal heritage of Peru and the country's mastery of fresh, simple preparations."
      }
    ]
  },
  {
    name: "Canada",
    foods: [
      {
        name: "Jiggs Dinner",
        imageUrls: ["https://drive.google.com/file/d/1_8BVHxWHjsnjf3mpDQ2gJPMXfa-gohOW/view?usp=drivesdk", "https://drive.google.com/file/d/1f-fCekrTGSPYEceFqDNTwwMLOEE0bU3R/view?usp=drivesdk", "https://drive.google.com/file/d/1TBk8IB5gGdq1TIS6MPleT4WzJbYV2Pdv/view?usp=drivesdk"],
        originCity: "Toronto",
        originCityLat: 43.6532,
        originCityLng: -79.3832,
        description: "A traditional Newfoundland meal of salt beef, cabbage, and root vegetables. This hearty dish represents the maritime heritage of Atlantic Canada and the country's love for simple, satisfying meals."
      },
      {
        name: "Butter Tart",
        imageUrls: ["https://drive.google.com/file/d/1pBOSAVB0hlPQfSFSFDmhwN_F7ALliv5x/view?usp=drivesdk", "https://drive.google.com/file/d/1ZiuFbkFOpEbO6SeOF215YObn8AZ_fVmk/view?usp=drivesdk", "https://drive.google.com/file/d/18XdCmKAb8IgRYYg9Rw98iiOYBXVvl3LA/view?usp=drivesdk"],
        originCity: "Toronto",
        originCityLat: 43.6532,
        originCityLng: -79.3832,
        description: "A Canadian pastry filled with butter, sugar, and eggs. This sweet treat represents the country's love for simple desserts and its mastery of traditional baking techniques."
      },
      {
        name: "Poutine",
        imageUrls: ["https://drive.google.com/file/d/1iVa5deVNjdHiPo8vFi2tAa6yYXv-IDnM/view?usp=drivesdk", "https://drive.google.com/file/d/1ZA6XQ-PkfrAxD0fO7J0hTycZzO3fUlJJ/view?usp=drivesdk"],
        originCity: "Toronto",
        originCityLat: 43.6532,
        originCityLng: -79.3832,
        description: "French fries topped with cheese curds and gravy. This iconic Canadian dish represents the country's fusion of French and British influences and its love for hearty comfort food."
      }
    ]
  },
  {
    name: "Iceland",
    foods: [
      {
        name: "Hákarl",
        imageUrls: [],
        originCity: "Reykjavik",
        originCityLat: 64.1466,
        originCityLng: -21.9426,
        description: "Fermented shark meat that's buried underground for months. This acquired taste represents the resourcefulness of Icelandic cuisine and the country's mastery of traditional preservation techniques."
      },
      {
        name: "Kjötsúpa Lamb Soup",
        imageUrls: [],
        originCity: "Reykjavik",
        originCityLat: 64.1466,
        originCityLng: -21.9426,
        description: "A traditional Icelandic soup made with lamb and root vegetables. This hearty dish represents the country's love for simple, nourishing meals and its mastery of slow-cooking techniques."
      },
      {
        name: "Pylsur",
        imageUrls: [],
        originCity: "Reykjavik",
        originCityLat: 64.1466,
        originCityLng: -21.9426,
        description: "Icelandic hot dogs made with lamb, pork, and beef. This popular street food represents the country's adaptation of international dishes to local tastes and ingredients."
      }
    ]
  },
  {
    name: "South Korea",
    foods: [
      {
        name: "Sannakji",
        imageUrls: [],
        originCity: "Seoul",
        originCityLat: 37.5665,
        originCityLng: 126.978,
        description: "Live octopus that's cut up and served immediately while still moving. This extreme delicacy represents the adventurous nature of Korean cuisine and the country's love for fresh, unique textures."
      },
      {
        name: "Bibimbap",
        imageUrls: [],
        originCity: "Seoul",
        originCityLat: 37.5665,
        originCityLng: 126.978,
        description: "A Korean rice bowl topped with various vegetables, meat, and a fried egg. This colorful dish represents the balance of Korean cuisine and the country's mastery of combining different flavors and textures."
      },
      {
        name: "Kimchi",
        imageUrls: [],
        originCity: "Seoul",
        originCityLat: 37.5665,
        originCityLng: 126.978,
        description: "Fermented vegetables, usually cabbage, that's a staple of Korean cuisine. This tangy side dish represents the importance of fermentation in Korean cooking and the country's mastery of preserving techniques."
      }
    ]
  },
  {
    name: "Vietnam",
    foods: [
      {
        name: "Tiết Canh",
        imageUrls: [],
        originCity: "Ho Chi Minh City",
        originCityLat: 10.8231,
        originCityLng: 106.6297,
        description: "A Vietnamese dish made with raw duck blood and various herbs. This adventurous delicacy represents the bold flavors of Vietnamese cuisine and the country's mastery of balancing strong tastes."
      },
      {
        name: "Bánh Mì",
        imageUrls: ["https://drive.google.com/file/d/1NVcdJUbNsQbJ4NaL2-qncgZLao7XVaIH/view?usp=drivesdk", "https://drive.google.com/file/d/1TXeMMAuBI2x764oPjdq6T8VNuFfHESfN/view?usp=drivesdk", "https://drive.google.com/file/d/1LEv7GGG1xkt9Ztwl8xzflT1QYCPUrZ5a/view?usp=drivesdk"],
        originCity: "Ho Chi Minh City",
        originCityLat: 10.8231,
        originCityLng: 106.6297,
        description: "A Vietnamese sandwich made with French bread and various fillings. This fusion dish represents the influence of French colonialism on Vietnamese cuisine and the country's ability to adapt foreign techniques."
      },
      {
        name: "Phở",
        imageUrls: ["https://drive.google.com/file/d/1Z2oRH22hcNtgcB8X90UQfqC2UFe_PpFv/view?usp=drivesdk", "https://drive.google.com/file/d/1ZfhEiW_mHvllGbgQmm2f1rwtFz2uIR2n/view?usp=drivesdk", "https://drive.google.com/file/d/1Ou3ZkvyA2T9Rlh_th8BoQ2fHWQnlQU0C/view?usp=drivesdk"],
        originCity: "Ho Chi Minh City",
        originCityLat: 10.8231,
        originCityLng: 106.6297,
        description: "A Vietnamese noodle soup made with beef or chicken broth and rice noodles. This comforting dish represents the soul of Vietnamese cuisine and the country's mastery of complex, aromatic broths."
      }
    ]
  },
  {
    name: "Thailand",
    foods: [
      {
        name: "Green Curry",
        imageUrls: [],
        originCity: "Bangkok",
        originCityLat: 13.7563,
        originCityLng: 100.5018,
        description: "A spicy Thai curry made with green chilies, coconut milk, and various vegetables. This vibrant dish represents the bold flavors of Thai cuisine and the country's mastery of balancing heat with creaminess."
      },
      {
        name: "Larb Mote Daeng",
        imageUrls: [],
        originCity: "Bangkok",
        originCityLat: 13.7563,
        originCityLng: 100.5018,
        description: "A spicy Thai salad made with red ant eggs, herbs, and chili. This unique dish represents the adventurous nature of Thai cuisine and the country's use of unusual but flavorful ingredients."
      },
      {
        name: "Tom Yum Goong",
        imageUrls: [],
        originCity: "Bangkok",
        originCityLat: 13.7563,
        originCityLng: 100.5018,
        description: "A hot and sour Thai soup made with shrimp, lemongrass, and galangal. This aromatic dish represents the perfect balance of Thai flavors and the country's mastery of complex, layered tastes."
      },
      {
        name: "Pad Thai",
        imageUrls: [],
        originCity: "Bangkok",
        originCityLat: 13.7563,
        originCityLng: 100.5018,
        description: "A stir-fried noodle dish that has become Thailand's most famous export. This sweet and savory dish represents the country's ability to create globally appealing flavors while maintaining its culinary identity."
      }
    ]
  },
  {
    name: "Spain",
    foods: [
      {
        name: "Percebes Gooseneck Barnacles",
        imageUrls: [],
        originCity: "Madrid",
        originCityLat: 40.4168,
        originCityLng: -3.7038,
        description: "A rare and expensive delicacy harvested from dangerous rocky coastlines. This unique seafood represents the adventurous spirit of Spanish cuisine and the country's mastery of simple preparations that let quality ingredients shine."
      },
      {
        name: "Tortilla Española",
        imageUrls: [],
        originCity: "Madrid",
        originCityLat: 40.4168,
        originCityLng: -3.7038,
        description: "A Spanish omelette made with eggs, potatoes, and onions. This simple yet satisfying dish represents the foundation of Spanish cuisine and the country's mastery of egg-based dishes."
      },
      {
        name: "Paella Valenciana",
        imageUrls: ["https://drive.google.com/uc?export=view&id=17YVZv_KIBXczTBEOxm_gd3dVIIaSPXg7"],
        originCity: "Madrid",
        originCityLat: 40.4168,
        originCityLng: -3.7038,
        description: "A rice dish that originated in Valencia, traditionally made with rabbit, chicken, and beans. This iconic dish represents the diversity of Spanish cuisine and the country's mastery of rice cooking techniques."
      }
    ]
  },
  {
    name: "France",
    foods: [
      {
        name: "Profiteroles",
        imageUrls: [],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "Small choux pastry balls filled with cream and topped with chocolate sauce. This elegant dessert represents the sophistication of French pastry-making and the country's influence on world cuisine."
      },
      {
        name: "Quiche Lorraine",
        imageUrls: [],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "A savory tart made with eggs, cream, and bacon in a pastry crust. This classic represents the elegance of French home cooking and the country's mastery of pastry techniques."
      },
      {
        name: "Chocolate Éclair",
        imageUrls: [],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "A pastry made with choux dough filled with cream and topped with chocolate icing. This elegant dessert represents the artistry of French pastry-making and the country's influence on world cuisine."
      },
      {
        name: "French Onion Soup",
        imageUrls: [],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "A rich soup made with caramelized onions, beef broth, and topped with melted cheese. This classic represents the depth of French flavors and the country's ability to create comfort food with sophisticated techniques."
      },
      {
        name: "Crêpes",
        imageUrls: [],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "Thin pancakes that can be sweet or savory, representing the versatility of French cuisine. This beloved dish represents the country's mastery of simple techniques and the importance of quality ingredients in French cooking."
      },
      {
        name: "Foie Gras",
        imageUrls: [],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "A luxury food product made from the liver of a duck or goose that has been specially fattened. This controversial delicacy represents the sophistication of French cuisine and the country's mastery of traditional techniques."
      },
      {
        name: "Escargots de Bourgogne",
        imageUrls: [],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "Snails cooked in garlic butter and served in their shells. This classic French appetizer represents the country's adventurous palate and its mastery of simple yet sophisticated preparations."
      },
      {
        name: "Coq au Vin",
        imageUrls: ["https://drive.google.com/uc?export=view&id=1Am_xjSDVf0zXcP4ggyEcIqRbw4ZYAlX7"],
        originCity: "Paris",
        originCityLat: 48.8566,
        originCityLng: 2.3522,
        description: "A classic French dish of chicken braised with wine, mushrooms, and onions. This hearty stew represents the essence of French country cooking and the importance of wine in French culinary traditions."
      }
    ]
  },
  {
    name: "USA",
    foods: [
      {
        name: "Peanut Butter and Jelly Sandwich",
        imageUrls: [],
        originCity: "New York",
        originCityLat: 40.7128,
        originCityLng: -74.006,
        description: "A simple sandwich made with peanut butter and fruit jelly on bread. This childhood favorite represents American simplicity and the country's love for sweet and savory combinations."
      },
      {
        name: "Chocolate Chip Cookies",
        imageUrls: [],
        originCity: "Massachusetts",
        originCityLat: 42.4072,
        originCityLng: -71.3824,
        description: "Soft, chewy cookies loaded with chocolate chips that have become America's favorite cookie. This homemade treat represents the country's baking traditions and the importance of comfort foods in American culture."
      },
      {
        name: "Key Lime Pie",
        imageUrls: [],
        originCity: "Key West",
        originCityLat: 24.5551,
        originCityLng: -81.782,
        description: "A tangy dessert made with Key lime juice, sweetened condensed milk, and a graham cracker crust. This refreshing pie represents the tropical flavors of Florida and is considered the state's official dessert."
      },
      {
        name: "Clam Chowder",
        imageUrls: [],
        originCity: "Boston",
        originCityLat: 42.3601,
        originCityLng: -71.0589,
        description: "A creamy New England soup made with clams, potatoes, and onions. This hearty seafood soup represents the coastal cuisine of the northeastern United States and is a beloved comfort food in cold weather."
      },
      {
        name: "Philly Cheesesteak",
        imageUrls: [],
        originCity: "Philadelphia",
        originCityLat: 39.9526,
        originCityLng: -75.1652,
        description: "A sandwich made with thinly sliced beefsteak and melted cheese on a long roll. This Philadelphia classic represents the city's working-class roots and has become one of America's most iconic street foods."
      },
      {
        name: "Chicken and Waffles",
        imageUrls: ["https://drive.google.com/file/d/1P7NclDqYkoNGwTBCv7IO58EfT6lY24Ca/view?usp=drivesdk", "https://drive.google.com/file/d/1hZ2Rb_SfG0vUBAIP6kx5gDRGF7nvqNIW/view?usp=drivesdk", "https://drive.google.com/file/d/1uJGAhiYfJlMhLVf_10JDlsXQHLzUjYq6/view?usp=drivesdk"],
        originCity: "Los Angeles",
        originCityLat: 34.0522,
        originCityLng: -118.2437,
        description: "A unique combination of crispy fried chicken served over fluffy waffles, often drizzled with maple syrup. This soul food favorite represents the fusion of Southern and breakfast traditions in American cuisine."
      },
      {
        name: "Grilled Cheese Sandwich",
        imageUrls: [],
        originCity: "New York",
        originCityLat: 40.7128,
        originCityLng: -74.006,
        description: "A simple sandwich made with bread and melted cheese, often grilled until golden and crispy. This comfort food classic represents American simplicity and the country's love for satisfying, easy-to-make meals."
      },
      {
        name: "Meatloaf",
        imageUrls: [],
        originCity: "Ohio",
        originCityLat: 40.3888,
        originCityLng: -82.7649,
        description: "A ground meat mixture baked in a loaf pan and often glazed with ketchup. This family dinner staple represents American home cooking and the country's tradition of simple, nourishing meals."
      },
      {
        name: "Chicken Pot Pie",
        imageUrls: [],
        originCity: "Pennsylvania",
        originCityLat: 40.2732,
        originCityLng: -76.8754,
        description: "A savory pie filled with chicken, vegetables, and gravy, topped with a flaky pastry crust. This comfort food classic represents American home cooking and the country's love for hearty, satisfying meals."
      },
      {
        name: "Caesar Salad",
        imageUrls: ["https://drive.google.com/file/d/1eJe0FJ9xZfLsOGEQAmC8p7jMj9mLTKAL/view?usp=drivesdk", "https://drive.google.com/file/d/1lhDzinm2eJi5BMPpwnjoGcPGSK6QjZWj/view?usp=drivesdk", "https://drive.google.com/file/d/14U5CrkRpI-8Zlml2lM9eMra7aeGj-oF1/view?usp=drivesdk"],
        originCity: "Tijuana",
        originCityLat: 32.5149,
        originCityLng: -117.0382,
        description: "A crisp romaine lettuce salad with croutons, parmesan cheese, and a creamy Caesar dressing. This classic salad represents the sophistication of American cuisine and its ability to create timeless dishes."
      },
      {
        name: "Buffalo Wings",
        imageUrls: ["https://drive.google.com/file/d/1l1e8xJFwY2IV437tMGibcVvJTbWS8RmY/view?usp=drivesdk", "https://drive.google.com/file/d/1F9guZ9Wx3fGljV9dknV-VogfGIR6nVGL/view?usp=drivesdk", "https://drive.google.com/file/d/1OqQIP2EYFiUV_VmvmoELK8c7mPuUrbdp/view?usp=drivesdk"],
        originCity: "Buffalo",
        originCityLat: 42.8864,
        originCityLng: -78.8784,
        description: "Spicy chicken wings coated in hot sauce and butter, served with blue cheese dressing. This finger food favorite represents American bar culture and the country's love for bold, spicy flavors."
      },
      {
        name: "Rocky Mountain Oysters",
        imageUrls: [],
        originCity: "Denver",
        originCityLat: 39.7392,
        originCityLng: -104.9903,
        description: "A true test of culinary bravery, these are actually bull testicles that are peeled, coated in flour, and deep-fried. This unusual delicacy represents the adventurous spirit of the American West and the resourcefulness of frontier cooking."
      },
      {
        name: "BBQ Ribs",
        imageUrls: ["https://drive.google.com/file/d/1VhsowKKJzjFe9FOdRiwjmRWP33irlYtQ/view?usp=drivesdk", "https://drive.google.com/file/d/14ry1JB0DkNg-NMW8k_4fQSFti3IDxv75/view?usp=drivesdk", "https://drive.google.com/file/d/1OkJRh-zjcuii-ZIQNS2-LZKldJPUgdPM/view?usp=drivesdk"],
        originCity: "Kansas City",
        originCityLat: 39.0997,
        originCityLng: -94.5786,
        description: "Slow-cooked pork ribs slathered in tangy barbecue sauce represent the heart of American barbecue culture. This finger-licking dish showcases the country's mastery of low-and-slow cooking techniques and regional sauce variations."
      },
      {
        name: "Hamburger",
        imageUrls: [],
        originCity: "New York",
        originCityLat: 40.7128,
        originCityLng: -74.006,
        description: "The hamburger as we know it today evolved from German immigrants bringing their Hamburg steak to America in the 19th century. This iconic American food represents the country's love for simple, satisfying meals and has become a global symbol of American cuisine."
      }
    ]
  },
  {
    name: "China",
    foods: [
      {
        name: "Fortune Cookies",
        imageUrls: [],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "Crispy cookies with a fortune inside, often served at Chinese restaurants. This American-Chinese invention represents the fusion of cultures and the global reach of Chinese cuisine."
      },
      {
        name: "Chow Mein",
        imageUrls: [],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "A Chinese stir-fried noodle dish with vegetables and meat. This popular dish represents the diversity of Chinese noodle cuisine and the country's mastery of stir-frying techniques."
      },
      {
        name: "Mooncakes",
        imageUrls: [],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "Traditional Chinese pastries filled with sweet or savory fillings, traditionally eaten during the Mid-Autumn Festival. This cultural dish represents the importance of food in Chinese celebrations and the country's mastery of pastry techniques."
      },
      {
        name: "Wonton Soup",
        imageUrls: [],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "A clear soup with delicate dumplings filled with meat or shrimp. This comforting dish represents the artistry of Chinese dumpling-making and the country's emphasis on balance in flavors and textures."
      },
      {
        name: "Char Siu",
        imageUrls: [],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "Chinese barbecued pork that's marinated and roasted until caramelized. This flavorful dish represents the sophistication of Chinese cooking techniques and the country's mastery of marinades and roasting."
      },
      {
        name: "Century Egg",
        imageUrls: [],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "A Chinese delicacy made by preserving duck, chicken, or quail eggs in a mixture of clay, ash, salt, quicklime, and rice hulls for several weeks. This unique dish represents the country's mastery of preservation techniques and its love for bold, acquired tastes."
      },
      {
        name: "Dim Sum",
        imageUrls: [],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "A traditional Chinese meal of small plates served with tea. This social dining experience represents the country's mastery of dumpling-making and the importance of sharing food in Chinese culture."
      },
      {
        name: "Peking Duck",
        imageUrls: ["https://drive.google.com/uc?export=view&id=1hJ3wKIARLMeRyve-fpzOz-VWtr_keHqT", "https://drive.google.com/uc?export=view&id=1hh14XWa4Lm0pBhJslxB1ezM8n5_BkOks", "https://drive.google.com/uc?export=view&id=1zOMXEVyRuuTKWqROJEtC5qanHJW9RDvW"],
        originCity: "Beijing",
        originCityLat: 39.9042,
        originCityLng: 116.4074,
        description: "A famous Chinese dish of crispy duck served with pancakes and hoisin sauce. This imperial dish represents the pinnacle of Chinese cooking techniques and the country's mastery of roasting and presentation."
      }
    ]
  },
  {
    name: "India",
    foods: [
      {
        name: "Raita",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A cooling yogurt-based side dish with vegetables and spices. This refreshing accompaniment represents the balance of Indian cuisine and the country's mastery of contrasting flavors and temperatures."
      },
      {
        name: "Vindaloo",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A spicy curry dish that originated in Goa with Portuguese influence. This fiery dish represents the fusion of Indian and Portuguese cuisines and the country's mastery of complex spice combinations."
      },
      {
        name: "Kulfi",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A traditional Indian ice cream made with milk, sugar, and various flavorings. This frozen dessert represents the creativity of Indian sweets and the country's ability to create cooling treats for hot climates."
      },
      {
        name: "Rogan Josh",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A fragrant lamb curry from Kashmir made with yogurt, onions, and aromatic spices. This elegant dish represents the sophistication of Indian cuisine and the country's mastery of complex spice blends."
      },
      {
        name: "Chana Masala",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A spicy chickpea curry that's a staple of North Indian cuisine. This protein-rich dish represents the importance of legumes in Indian cooking and the country's mastery of spice combinations."
      },
      {
        name: "Palak Paneer",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A vegetarian curry made with cottage cheese in a creamy spinach sauce. This nutritious dish represents the diversity of Indian vegetarian cuisine and the country's mastery of combining vegetables with dairy."
      },
      {
        name: "Chicken Tikka Masala",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A popular curry dish made with marinated chicken in a spiced tomato and cream sauce. This beloved dish represents the fusion of Indian and British cuisines and has become one of the world's most popular Indian dishes."
      },
      {
        name: "Bheja Fry",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A spicy Indian dish made with brain (usually goat or sheep) that's marinated and fried. This adventurous delicacy represents the country's use of all parts of the animal and its mastery of bold, complex flavors."
      },
      {
        name: "Samosa",
        imageUrls: [],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "Triangular pastries filled with spiced potatoes, peas, and sometimes meat. This popular street food represents the diversity of Indian snacks and the country's mastery of pastry-making techniques."
      },
      {
        name: "Biryani",
        imageUrls: ["https://drive.google.com/uc?export=view&id=1ysms4acRrNy0jPAf6szoTz-lINa5l5aY", "https://drive.google.com/uc?export=view&id=1YgpuMvUpK2DHvRkjlpe5_wDcqvQ8ZRl3"],
        originCity: "New Delhi",
        originCityLat: 28.6139,
        originCityLng: 77.209,
        description: "A fragrant rice dish layered with spiced meat and cooked slowly. This royal dish represents the sophistication of Indian cuisine and the country's mastery of complex layering techniques."
      }
    ]
  },
  {
    name: "Mexico",
    foods: [
      {
        name: "Guacamole",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "A dip made from mashed avocados, lime juice, and various seasonings. This fresh dish represents the importance of avocados in Mexican cuisine and the country's mastery of simple, flavorful combinations."
      },
      {
        name: "Tres Leches Cake",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "A sponge cake soaked in three types of milk and topped with whipped cream. This moist dessert represents the fusion of Mexican and European cuisines and the country's mastery of dairy-based sweets."
      },
      {
        name: "Pozole",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "A traditional soup made with hominy, meat, and chili peppers. This hearty dish represents the ancient roots of Mexican cuisine and the country's mastery of complex, layered flavors."
      },
      {
        name: "Tostadas",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "Crispy fried tortillas topped with beans, meat, cheese, and vegetables. This versatile dish represents the creativity of Mexican cuisine and the country's love for contrasting textures and flavors."
      },
      {
        name: "Enchiladas",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "Corn tortillas rolled around a filling and covered with chili sauce. This classic dish represents the heart of Mexican cuisine and the country's mastery of corn-based foods and chili peppers."
      },
      {
        name: "Escamoles",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "Known as \"insect caviar,\" escamoles are the edible larvae and pupae of ants. Harvested from the roots of agave plants, they have a slightly nutty, buttery taste and a texture similar to cottage cheese when cooked."
      },
      {
        name: "Mole Poblano",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "A legendary sauce said to have been invented in a convent in Puebla. Mole is incredibly complex, sometimes containing over 20 ingredients like chili peppers, nuts, spices, and a touch of chocolate, creating a rich, dark sauce."
      },
      {
        name: "Tacos al Pastor",
        imageUrls: [],
        originCity: "Mexico City",
        originCityLat: 19.4326,
        originCityLng: -99.1332,
        description: "This dish has a fascinating history, adapted from the vertical spit-roasting shawarma technique brought by Lebanese immigrants. It's made with marinated pork, which is shaved off a rotating trompo and served with pineapple."
      }
    ]
  },
  {
    name: "Japan",
    foods: [
      {
        name: "Onigiri",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "Japanese rice balls that are often filled with various ingredients and wrapped in nori seaweed. This portable snack represents the importance of rice in Japanese culture and the country's creativity with simple ingredients."
      },
      {
        name: "Karaage",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "Japanese fried chicken that's marinated and coated with flour before frying. This crispy dish represents the Japanese mastery of frying techniques and the country's attention to texture and flavor."
      },
      {
        name: "Mochi",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "Sweet rice cakes made from glutinous rice and often filled with sweet bean paste. This traditional treat represents the importance of rice in Japanese culture and the country's mastery of traditional techniques."
      },
      {
        name: "Chirashi",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "A bowl of sushi rice topped with various sashimi and vegetables. This colorful dish represents the artistry of Japanese presentation and the country's love for fresh, seasonal ingredients."
      },
      {
        name: "Sashimi",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "Fresh raw fish or seafood sliced into thin pieces and served without rice. This elegant dish represents the pinnacle of Japanese cuisine and the country's emphasis on fresh, quality ingredients."
      },
      {
        name: "Udon",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "Thick wheat noodles served in a mild broth with various toppings. This comforting dish represents the diversity of Japanese noodle cuisine and the country's mastery of simple, satisfying flavors."
      },
      {
        name: "Tonkatsu",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "A breaded and deep-fried pork cutlet that's crispy on the outside and tender inside. This popular dish represents the Japanese adaptation of Western cooking techniques and the country's attention to texture and presentation."
      },
      {
        name: "Shirako",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "A true delicacy for the adventurous, Shirako translates to \"white children.\" It's the milt, or sperm sacs, of male cod, praised for its soft, creamy texture that melts in your mouth when served poached or lightly grilled."
      },
      {
        name: "Ramen",
        imageUrls: [],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "Though its roots are in Chinese noodle soups, ramen was popularized in Japan in the late 19th century. Each region has its own beloved version, from the rich tonkotsu of Fukuoka to the miso ramen of Sapporo."
      },
      {
        name: "Sushi",
        imageUrls: ["https://drive.google.com/uc?export=view&id=1YBJv3eTKs2CpB4byoirG2qcMmn-nAJGc", "https://drive.google.com/uc?export=view&id=16GTvm2zHDKUPsl75xzqq_3G9sghKQas2", "https://drive.google.com/uc?export=view&id=1wTQ8BeO5w1xysFNJhAAYGmj3csyT7EQY"],
        originCity: "Tokyo",
        originCityLat: 35.6762,
        originCityLng: 139.6503,
        description: "What began as a method for preserving fish in fermented rice in Southeast Asia evolved in Edo-period Japan into the culinary art form we know today, focusing on the freshness of the fish itself."
      }
    ]
  },
  {
    name: "Italy",
    foods: [
      {
        name: "Minestrone",
        imageUrls: [],
        originCity: "Milan",
        originCityLat: 45.4642,
        originCityLng: 9.19,
        description: "A thick Italian vegetable soup made with beans, pasta, and various vegetables. This hearty soup represents the diversity of Italian cuisine and the country's mastery of simple, nourishing dishes."
      },
      {
        name: "Bruschetta",
        imageUrls: ["https://drive.google.com/file/d/1-VAMxdXI2KY6ts61ZXHlt3qT1ViFm4AT/view?usp=drivesdk", "https://drive.google.com/file/d/1GB7N8Eg3qEjdw8CqG17f2YFAcQDN37EZ/view?usp=drivesdk", "https://drive.google.com/file/d/1z7PY2GioyOBq-A7H623QrLgrKflrhKPo/view?usp=drivesdk"],
        originCity: "Tuscany",
        originCityLat: 43.7696,
        originCityLng: 11.2558,
        description: "Grilled bread rubbed with garlic and topped with olive oil, salt, and various toppings. This simple appetizer represents the essence of Italian cuisine and the country's emphasis on quality ingredients."
      },
      {
        name: "Cannoli",
        imageUrls: ["https://drive.google.com/file/d/1naqh-y7KNdN1k7VnurfJqHth9dQ6SRZj/view?usp=drivesdk", "https://drive.google.com/file/d/1hUF_5vr7pOjen3Q9Yi9YerkCYnL0Lx4h/view?usp=drivesdk", "https://drive.google.com/file/d/1PCXvbZhMah1_f_NIdASzIwDm704hBHNr/view?usp=drivesdk"],
        originCity: "Sicily",
        originCityLat: 37.5994,
        originCityLng: 14.0154,
        description: "Sicilian pastry tubes filled with sweet ricotta cheese and often studded with chocolate chips or candied fruit. This elegant dessert represents the artistry of Italian pastry-making and the country's mastery of sweet treats."
      },
      {
        name: "Arancini",
        imageUrls: ["https://drive.google.com/file/d/1R8HKgrW_jNamhiG7wqDvpARZUg0aWZbZ/view?usp=drivesdk", "https://drive.google.com/file/d/1I_3jgCF2oCxHiRBoH0iviekuc2hsBO0H/view?usp=drivesdk", "https://drive.google.com/file/d/1jwA0ViBt4sSmbk5U7PaKvwaWmqHTgLYT/view?usp=drivesdk"],
        originCity: "Sicily",
        originCityLat: 37.5994,
        originCityLng: 14.0154,
        description: "Sicilian rice balls that are stuffed, coated with breadcrumbs, and deep-fried. This street food favorite represents the creativity of Italian cuisine and the country's ability to transform simple ingredients into extraordinary dishes."
      },
      {
        name: "Panna Cotta",
        imageUrls: [],
        originCity: "Piedmont",
        originCityLat: 45.0703,
        originCityLng: 7.6869,
        description: "A traditional Italian dessert made with sweetened cream thickened with gelatin. This elegant dessert represents the refinement of Italian sweets and the country's mastery of simple yet sophisticated techniques."
      },
      {
        name: "Spaghetti Carbonara",
        imageUrls: ["https://drive.google.com/file/d/1_AWhNrRi9K0KRMkV0uQVDWQLpI5fT6oo/view?usp=drivesdk", "https://drive.google.com/file/d/1wCXiVV6Sn8d_XJ3kfwre7jy7YZOymxyf/view?usp=drivesdk", "https://drive.google.com/file/d/1Mr-ffUGWfI6QoDi2qXCnz4W-aDWOPylP/view?usp=drivesdk"],
        originCity: "Rome",
        originCityLat: 41.9028,
        originCityLng: 12.4964,
        description: "A Roman pasta dish made with eggs, cheese, pancetta, and black pepper. This creamy pasta represents the sophistication of Italian cooking and the importance of technique in creating perfect textures."
      },
      {
        name: "Margherita Pizza",
        imageUrls: ["https://drive.google.com/file/d/1B6VeFScJUzVeAyKxthvPsEc7DgFH3NyD/view?usp=drivesdk", "https://drive.google.com/file/d/1JsZHQ5TMCUDX2MT_7_sUlBasWY5ggmQ0/view?usp=drivesdk", "https://drive.google.com/file/d/12KdUyJpWSS1JPCIghlG_6WrMxehIdg2F/view?usp=drivesdk"],
        originCity: "Naples",
        originCityLat: 40.8518,
        originCityLng: 14.2681,
        description: "A simple pizza topped with tomato sauce, mozzarella, and fresh basil. This classic represents the essence of Italian cuisine and the country's mastery of simple, quality ingredients."
      },
      {
        name: "Casu Marzu",
        imageUrls: [],
        originCity: "Sardinia",
        originCityLat: 40.1209,
        originCityLng: 9.0129,
        description: "An infamous Sardinian sheep milk cheese known for containing live insect larvae. The acid from the larvae breaks down the cheese's fats, making the texture very soft with a strong, pungent flavor."
      }
    ]
  }
];